### ISSUE TITLE
The repository name is too generic

### ISSUE THREAD

**Issue by arnau** [ustwo/docker-node-boilerplate#1]
@daaain, I think the repository name and the docker image have to have a better name, probably explaining what technology are you bundling.  Something like `docker-node` or `docker-express` or `docker-react` would do the trick and would be aligned with the other generic image we have, the `docker-ruby`.

**Comment by daaain** [comment]
Thanks @arnau, good point, renamed it to docker-node-boilerplate (at least for now). I didn't intend to keep it Express / React specific, but thought I'd leave them in there as it sounds useful to have some frameworks in place to see how would you do things like template compilation, server startup, etc. But on the other hand it's definitely Node specific now so good to make that clear :)

I'm still thinking though what to do with Ruby, say if you either wanted Sass compiler or use Sinatra on the server side, etc then it's useful. Do you think it would be too much of a bloat to have both Ruby and Node in the container preinstalled? The intention after all is to give a quick start with a more generic container, which you would naturally evolve as the project takes shape.

**Comment by arnau** [comment]
At first yes, the whole point of Docker is to have manageable images with an specific purpose.  That said, there are cases were is convenient to have something less clean but that is true only if you don't care at all about keeping parity with a possible production environment.

So, I'm afraid it's a project-basis decision.

I would suggest defining a clear objective in the README so anyone using this can expect a certain quality/set of tools.  That way the evolution of the image will be better driven.  What do you think?

**Comment by daaain** [comment]
Thanks a lot for the comments! I just added some clarification in the README.

I think I'll take it somewhere in the direction of the [Frontend Boilerplate](https://github.com/newaeonweb/frontendboilerplate), but with Gulp instead of Grunt and seeing if it makes sense running everything inside the container rather than having to have Node locally, etc. Though not sure yet how will I get LiveReload working then!

**Comment by arnau** [comment]
No problem :grinning: 

Take a second look to github.com/ustwo/westpac-deal (we renamed the project.)  Now we're using a bit more browserify, and I added a prototype for rendering RAML files.
